<span class="pull-right">
    <a href="#" class="btn btn-success">Insert</a>
    <a href="#" class="btn btn-warning">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
</span>

<h1>Audit Entity Association</h1>

<?php $paginator = $this->auditAssociationPaginator($this->page, $this->revisionEntity, $this->joinTable); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/association', array('route' => 'stuki-workspace/association'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Target</th>
            <th>Source</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/association', array('route' => 'stuki-workspace/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $association) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revision',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity->getRevision()->getId());?>
                    @ <?php echo $this->StukiDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>

                </a>
            </td>

            <td>
                <?= $this->stukiRevisionEntityLink($association->getTargetRevisionEntity()); ?>
            </td>

            <td>
                <?= $this->stukiRevisionEntityLink($association->getSourceRevisionEntity()); ?>
            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/user-button',
                    array('user' => $revisionEntity->getRevision()->getUser())
                );?>
            </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
