<a class="btn btn-info pull-right" style="margin-left: 20px;" href="<?=
    $this->url('stuki-workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>

<a class="btn btn-info pull-right" href="<?=
    $this->url('stuki-workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<h1>Workspace Revisions By Entity</h1>

<?php $paginator = $this->stukiRevisionEntityPaginator($page, $this->entityClass); ?>

<table class="table table-striped table-hover table-bordered">
    <caption>
            <a href="<?=

                    $this->url(
                        'stuki-workspace/entity',
                        array(
                            'entityClass' => $this->entityClass,
                        )
                    );?>
        " class="btn btn-primary"><?= $this->escapeHtml($this->entityClass); ?></a>
    </caption>
    <thead>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/entity',
                    array(
                        'route' => 'stuki-workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/entity',
                    array(
                        'route' => 'stuki-workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
    </tfoot>

    <tbody>

<?php
foreach ($paginator as $revisionEntity) {
?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revision',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $revisionEntity->getRevision()->getId(); ?>
                    @ <?= $this->StukiDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?></a>
            </td>
            <td>
                <?= $this->stukiRevisionEntityLink($revisionEntity); ?>
            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revisionEntity->getRevision()->getUser()) {
                        echo $this->url('stuki-workspace/user', array('userId' => $revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('stuki-workspace/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revisionEntity->getRevision()->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('stuki.org@gmail.com', array('img_size' => 24));
                            echo ' Stuki Workspace';
                        }
                    ?>
                </a>
            </td>
            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/revision-approve',
                    array('revision' => $revisionEntity->getRevision())
                );
                ?>
            </td>
        </tr>
<?php
}
?>

    </tbody>
</table>

