<a class="btn btn-info pull-right" style="margin-left: 20px;" href="<?=
    $this->url('workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>

<a class="btn btn-info pull-right" href="<?=
    $this->url('workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<h1>Workspace Revisions By Entity</h1>

<?php $paginator = $this->workspaceRevisionEntityPaginator($page, $this->entityClass); ?>

<table class="table table-striped table-hover table-bordered">
    <caption>
            <a href="<?=

                    $this->url(
                        'workspace/entity',
                        array(
                            'entityClass' => $this->entityClass,
                        )
                    );?>
        " class="btn btn-primary"><?= $this->escapeHtml($this->entityClass); ?></a>
    </caption>
    <thead>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/entity',
                    array(
                        'route' => 'workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/entity',
                    array(
                        'route' => 'workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
    </tfoot>

    <tbody>

<?php
foreach ($paginator as $revisionEntity) {
?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $revisionEntity->getRevision()->getId(); ?>
                    @ <?= $this->WorkspaceDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?></a>
            </td>
            <td>
                <?= $this->workspaceRevisionEntityLink($revisionEntity); ?>
            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $revisionEntity->getRevision()->getUser())
                );?>
            </td>
            <td>
                <?= $this->partial(
                    'workspace/index/partial/revision-approve',
                    array('revision' => $revisionEntity->getRevision())
                );
                ?>
            </td>
        </tr>
<?php
}
?>

    </tbody>
</table>

