<a class="btn btn-info pull-right" style="margin-left: 20px;" href="<?=
    $this->url('stuki-workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>

<a class="btn btn-info pull-right" href="<?=
    $this->url('stuki-workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<h1>Workspace for
<a " class="btn btn-default" href="<?php
    echo $this->url('stuki-workspace/user', array('userId' => $this->user->getId()));
    ?>">

    <h3>
        <?= $this->gravatar($this->user->getEmail(), array('img_size' => 36)); ?>
        <?= $this->user ?>
    </h3>
</a>
</h1>


</h1>

<?php $paginator = $this->stukiWorkspacePaginator($this->page, $this->user->getId()); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/revision', array('route' => 'audit/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/revision', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revision',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->StukiDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
            ?>
                <div>
                    <?= $this->stukiRevisionEntityLink($revisionEntity); ?>
                </div>
            <?php
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/user-button',
                    array('user' => $revision->getUser())
                );?>
            </td>

            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/revision-approve',
                    array('revision' => $revision)
                );?>
            </td>

        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
