<a class="btn btn-info pull-right" href="<?=
    $this->url('stuki-workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>

<h1>Workspace Master</h1>

<?php $paginator = $this->stukiRevisionPaginator($this->page, array('approve' => 'approved')); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/revision', array('route' => 'audit/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/revision', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revision',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->StukiDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
            ?>
                <div>
                    <?= $this->stukiRevisionEntityLink($revisionEntity); ?>
                </div>
            <?php
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revision->getUser()) {
                        echo $this->url('stuki-workspace/user', array('userId' => $revision->getUser()->getId()));
                    } else {
                        echo $this->url('stuki-workspace/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revision->getUser()) {
                            echo $this->gravatar($revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revision->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('stuki.org@gmail.com', array('img_size' => 24));
                            echo ' Stuki Workspace';
                        }
                    ?>
                </a>
            </td>

            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/revision-approve',
                    array('revision' => $revision)
                );
                ?>
            </td>

        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
