<a class="btn btn-info pull-right" href="<?=
    $this->url('stuki-workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<?php
    use Doctrine\ORM\Mapping\ClassMetadataInfo;
?>

<h1>Workspace One To Many Relations</h1>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revision',
                        array(
                            'revisionId' => $this->revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->revisionEntity->getRevision()->getId(); ?>

                    @ <?php echo $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>
                </a>

            </td>

            <td>
                <?= $this->stukiRevisionEntityLink($revisionEntity); ?>
            </td>

            <td><?= $this->escapeHtml($this->revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($this->revisionEntity->getRevision()->getUser()) {
                        echo $this->url('stuki-workspace/user', array('userId' => $this->revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('stuki-workspace/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($this->revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($this->revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($this->revisionEntity->getRevision()->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>

<?php

    $paginator = $this->auditOneToManyPaginator(
        $this->page,
        $this->revisionEntity,
        $this->joinTable,
        $this->mappedBy
    );
?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/one-to-many', array('route' => 'audit/one-to-many'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'stuki-workspace/pagination/one-to-many', array('route' => 'audit/one-to-many'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $association) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('stuki-workspace/revisions',
                        array(
                            'revisionId' => $association->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $association->getRevision()->getId(); ?>

                    @ <?php echo $this->AuditDateTimeFormatter($association->getRevision()->getTimestamp()); ?>
                </a>

            </td>

            <td>
                <?= $this->stukiRevisionEntityLink($association); ?>
            </td>

            <td><?= $this->escapeHtml($association->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($association->getRevision()->getUser()) {
                        echo $this->url('stuki-workspace/user', array('userId' => $association->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('stuki-workspace/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($association->getRevision()->getUser()) {
                            echo $this->gravatar($association->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($association->getRevision()->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
