<h1>Workspace Revision</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        Revision
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <?= $this->escapeHtml($this->revision->getId());?>

                @ <?php echo $this->AuditDateTimeFormatter($this->revision->getTimestamp()); ?>
            </td>

            <td><?= $this->escapeHtml($this->revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($this->revision->getUser()) {
                        echo $this->url('stuki-workspace/user', array('userId' => $this->revision->getUser()->getId()));
                    } else {
                        echo $this->url('stuki-workspace/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($this->revision->getUser()) {
                            echo $this->gravatar($this->revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($this->revision->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
            <td>
                <?= $this->partial(
                    'stuki-workspace/index/partial/revision-approve',
                    array('revision' => $this->revision)
                );
                ?>
            </td>
        </tr>
    </tbody>
</table>


<?php
foreach ($this->revision->getRevisionEntities() as $revisionEntity) {
?>

<?= $this->stukiRevisionEntityLink($revisionEntity); ?>

<table class="table table-striped table-hover table-bordered ">
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->stukiWorkspaceService()->getEntityValues($revisionEntity->getAuditEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->AuditDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php
}
