<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>
    Workspace Comparission
</h1>

<table  class="table table-striped table-hover table-bordered ">
    <caption>
        Comparing <a href="<?=

                    $this->url(
                        'workspace/entity',
                        array(
                            'entityClass' => $revisionEntity_old->getWorkspaceEntity()->getWorkspaceEntityClass(),
                        )
                    );?>

        " class="btn btn-primary"><?php echo $this->escapeHtml($revisionEntity_old->getWorkspaceEntity()->getWorkspaceEntityClass()); ?></a>
        between

            <?= $this->workspaceRevisionEntityLink($revisionEntity_old); ?>

        and

            <?= $this->workspaceRevisionEntityLink($revisionEntity_new); ?>

    </caption>
    <thead>
        <tr>
            <th>Field</th>
            <th>Deleted</th>
            <th>Same</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>
        <?php $oldValues = $this->workspaceService()->getEntityValues($revisionEntity_old->getWorkspaceEntity()); ?>
        <?php $newValues = $this->workspaceService()->getEntityValues($revisionEntity_new->getWorkspaceEntity()); ?>

        <?php foreach ($oldValues as $field => $value): ?>
            <tr>
                <td><?= $field ?></td>
                <td>
                    <?php
                    if ($oldValues[$field] != $newValues[$field] and !$newValues[$field] and $oldValues[$field]) {
                    ?>

                        <?php if ($oldValues[$field] instanceof \DateTime): ?>
                            <?php echo $this->WorkspaceDateTimeFormatter($oldValues[$field]); ?>
                        <?php else: ?>
                            <?php echo  $this->escapeHtml($oldValues[$field]); ?>
                        <?php endif; ?></td>
                    <?php
                    }
                    ?>
                </td>
                <td>
                    <?php
                    if ($oldValues[$field] == $newValues[$field]){
                    ?>
                        <?php if ($oldValues[$field] instanceof \DateTime): ?>
                            <?php echo $this->WorkspaceDateTimeFormatter($oldValues[$field]); ?>
                        <?php else: ?>
                            <?php echo  $this->escapeHtml($oldValues[$field]); ?>
                        <?php endif; ?></td>
                    <?php
                    }
                    ?>
                </td>
                <td>
                    <?php
                    if ($oldValues[$field] != $newValues[$field] and $newValues[$field]) {
                    ?>

                        <?php if ($newValues[$field] instanceof \DateTime): ?>
                            <?php echo $this->WorkspaceDateTimeFormatter($newValues[$field]); ?>
                        <?php else: ?>
                            <?php echo  $this->escapeHtml($newValues[$field]); ?>
                        <?php endif; ?></td>
                    <?php
                    }
                    ?>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Old
    </caption>
    <thead>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $revisionEntity_old->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity_old->getRevision()->getId());?>
                    @ <?php echo $this->WorkspaceDateTimeFormatter($revisionEntity_old->getRevision()->getTimestamp()); ?>

                </a>


            </td>

            <td>
                <?= $this->workspaceRevisionEntityLink($revisionEntity_old); ?>
           </td>

        </tr>

        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->workspaceService()->getEntityValues($revisionEntity_old->getWorkspaceEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->WorkspaceDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        New
    </caption>

    <thead>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $revisionEntity_old->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity_old->getRevision()->getId());?>
                    @ <?php echo $this->WorkspaceDateTimeFormatter($revisionEntity_old->getRevision()->getTimestamp()); ?>

                </a>


            </td>
            <td>
                <?= $this->workspaceRevisionEntityLink($revisionEntity_new); ?>
            </td>
        </tr>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->workspaceService()->getEntityValues($revisionEntity_new->getWorkspaceEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->WorkspaceDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
