<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>Workspace Revisions By Entity</h1>

<?php $paginator = $this->workspaceRevisionEntityPaginator($page, $this->entityClass); ?>

<table class="table table-striped table-hover table-bordered">
    <caption>
            <a href="<?=

                    $this->url(
                        'workspace/entity',
                        array(
                            'entityClass' => $this->entityClass,
                        )
                    );?>
        " class="btn btn-primary"><?= $this->escapeHtml($this->entityClass); ?></a>
    </caption>
    <thead>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/entity',
                    array(
                        'route' => 'workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
        <?=
        $this->partial('workspace/index/partial/revision-table-header-row');
        ?>
    </thead>

    <tfoot>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/entity',
                    array(
                        'route' => 'workspace/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
    </tfoot>

    <tbody>
<?php
foreach ($paginator as $revisionEntity) {
    echo $this->partial('workspace/index/partial/revision-table-row', array(
        'revision' => $revisionEntity->getRevision()
    ));
}
?>
    </tbody>

</table>

