<a class="btn btn-info pull-right" href="<?=
    $this->url('workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>

<h1>Workspace Firehose</h1>

<?php $paginator = $this->workspaceRevisionPaginator($this->page); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/firehose', array('route' => 'workspace/firehose'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/firehose', array('route' => 'workspace/firehose'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->WorkspaceDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
            ?>
                <div>
                    <?= $this->workspaceRevisionEntityLink($revisionEntity); ?>
                </div>
            <?php
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $revision->getUser())
                );?>
            </td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/revision-approve',
                    array('revision' => $revision)
                );
                ?>
            </td>

        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
