<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>Workspace Firehose</h1>

<?php $paginator = $this->workspaceRevisionPaginator($this->page); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/firehose', array('route' => 'workspace/firehose'));
            ?>
            </th>
        </tr>
        <?=
        $this->partial('workspace/index/partial/revision-table-header-row');
        ?>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/firehose', array('route' => 'workspace/firehose'));
            ?>
        </th>
    </tfoot>
    <tbody>
        <?=
        $this->partial('workspace/index/partial/revision-table-rows', array(
            'revisions' => $paginator,
        ));
        ?>
    </tbody>
</table>
