<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>Workspace</h1>

Every user has their own workspace.  Users may add and edit any data.  Each data-changing transaction
is a revision.  All changes to the data
are encapsulated in each user's workspace as revisions and merged into the master workspace only after going
through a peer review process.  The master workspace is composed of all approved revisions.

<ol>
    <li>A user creates new data</li>
    <li>The user submits their workspace to be reviewed</li>
    <li>Another user reviews the submitted workspace and if everything is fine the reviewing user will merge the workspace into the master workspace.
    </li>
</ol>

A user may submit their workspace for review at any time.  The user's entire workspace from the point of submitting through it's beginning must
be approved at the same time.  This way every user only ever has one workspace and it must be correct as a whole in order to merge into the
master workspace.