<a class="btn btn-info pull-right" href="<?=
    $this->url('workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<h1>Workspace Master</h1>

<?php $paginator = $this->workspaceRevisionPaginator($this->page, array('approve' => 'approved')); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
            </th>
        </tr>
        <?=
        $this->partial('workspace/index/partial/revision-table-header-row');
        ?>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
        <?php
        foreach ($paginator as $revision) {
            echo $this->partial('workspace/index/partial/revision-table-row', array(
                'revision' => $revision
            ));
        }
        ?>
    </tbody>
</table>
