<?= $this->partial('workspace/index/partial/navigation'); ?>

<?php
    use Doctrine\ORM\Mapping\ClassMetadataInfo;
?>

<h1>Workspace One To Many Relations</h1>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $this->revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->revisionEntity->getRevision()->getId(); ?>

                    @ <?php echo $this->WorkspaceDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>
                </a>

            </td>

            <td>
                <?= $this->workspaceRevisionEntityLink($revisionEntity); ?>
            </td>

            <td><?= $this->escapeHtml($this->revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $this->revisionEntity->getRevision()->getUser())
                );?>
            </td>
            <td>
                <?= $this->partial(
                    'workspace/index/partial/revision-approve',
                    array('revision' => $this->revisionEntity->getRevision())
                );
                ?>
            </td>
        </tr>
    </tbody>
</table>

<?php

    $paginator = $this->workspaceOneToManyPaginator(
        $this->page,
        $this->revisionEntity,
        $this->joinTable,
        $this->mappedBy
    );
?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/one-to-many', array('route' => 'workspace/one-to-many'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/one-to-many', array('route' => 'workspace/one-to-many'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $association) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('workspace/revision',
                        array(
                            'revisionId' => $association->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $association->getRevision()->getId(); ?>

                    @ <?php echo $this->WorkspaceDateTimeFormatter($association->getRevision()->getTimestamp()); ?>
                </a>

            </td>

            <td>
                <?= $this->workspaceRevisionEntityLink($association); ?>
            </td>

            <td><?= $this->escapeHtml($association->getRevision()->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $association->getRevision()->getUser())
                );?>
            </td>
            <td>
                <?= $this->partial(
                    'workspace/index/partial/revision-approve',
                    array('revision' => $association->getRevision())
                );
                ?>
            </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
