<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>Workspace Revision</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        Revision
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <?= $this->escapeHtml($this->revision->getId());?>

                @ <?php echo $this->WorkspaceDateTimeFormatter($this->revision->getTimestamp()); ?>
            </td>

            <td><?= $this->escapeHtml($this->revision->getComment()); ?></td>

            <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $this->revision->getUser())
                );?>
            </td>
            <td>
                <?= $this->partial(
                    'workspace/index/partial/revision-approve',
                    array('revision' => $this->revision)
                );
                ?>
            </td>
        </tr>
    </tbody>
</table>


<?php
foreach ($this->revision->getRevisionEntities() as $revisionEntity) {
?>

<?= $this->workspaceRevisionEntityLink($revisionEntity); ?>

<table class="table table-striped table-hover table-bordered ">
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->workspaceService()->getEntityValues($revisionEntity->getWorkspaceEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->WorkspaceDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php
}
