<?= $this->partial('workspace/index/partial/navigation'); ?>

<h1>Workspace Revision</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        Revision
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tbody>
        <?=
        $this->partial('workspace/index/partial/revision-table-rows', array(
            'revisions' => array($this->revision),
        ));
        ?>
    </tbody>
</table>


<?php
foreach ($this->revision->getRevisionEntities() as $revisionEntity) {
?>

<?= $this->workspaceRevisionEntityLink($revisionEntity); ?>

<table class="table table-striped table-hover table-bordered ">
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->workspaceService()->getEntityValues($revisionEntity->getWorkspaceEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->WorkspaceDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php
}
