<?= $this->partial('workspace/index/partial/navigation'); ?>

<?php
    use Doctrine\ORM\Mapping\ClassMetadataInfo;
?>

<h1>Workspace Revision Entity</h1>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <?=
        $this->partial('workspace/index/partial/revision-table-header-row');
        ?>
    </thead>

    <tbody>
        <?=
            $this->partial('workspace/index/partial/revision-table-row', array(
                'revision' => $this->revisionEntity->getRevision(),
            ));
        ?>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Entity Values
    </caption>
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->workspaceService()->getEntityValues($this->revisionEntity->getWorkspaceEntity()) as $field => $value) {
            if ($field == 'password') continue;
            ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                <?php

                    // Is this an association?
                    if (in_array($field, array_keys($this->workspaceService()->getEntityAssociations($this->revisionEntity->getWorkspaceEntity())))) {
                        $associationRevisionEntity = $this->workspaceService()->getAssociationRevisionEntity($this->revisionEntity->getWorkspaceEntity(), $field, $value);

                        if ($associationRevisionEntity) {
                            echo $this->workspaceRevisionEntityLink($associationRevisionEntity);
                        }
                    } else {
                        if ($value instanceof \DateTime) {
                            echo $this->WorkspaceDateTimeFormatter($value);
                        } else {
                            echo $this->escapeHtml($value);
                        }
                    }
                    ?>
                </td>
            </tr>
        <?php
            }
        ?>

        <?php
        if ($this->workspaceService()->getEntityAssociations($this->revisionEntity->getWorkspaceEntity())) {
        ?>
            <tr>
                <th>Associations</th>
                <th>Link</th>
            </tr>

            <?php
                foreach($this->workspaceService()->getEntityAssociations($this->revisionEntity->getWorkspaceEntity()) as $field => $value) {
            ?>
                    <?php

                    switch ($value['type']) {
                        case ClassMetadataInfo::ONE_TO_ONE: # 1
                            echo 'one to one';
                            break;

                        case ClassMetadataInfo::MANY_TO_ONE: # 2
                            // Handled in field listing
                            break;

                        case ClassMetadataInfo::ONE_TO_MANY: # 4
                            // Verify an workspace class exists for this field
                            if (!class_exists('Workspace\\Entity\\' . str_replace('\\', '_', $value['targetEntity'])))
                                continue;


                            ?>
                            <tr>
                                <td><?php  echo $this->escapeHtml($field); ?></td>
                                <td>


                            <a class="workspace btn btn-<?php
                                switch ($this->revisionEntity->getRevisionType()) {
                                    case 'INS':
                                        echo 'success';
                                        break;
                                    case 'UPD':
                                        echo 'warning';
                                        break;
                                    case 'DEL':
                                        echo 'danger';
                                        break;
                                    default:
                                        echo 'info';
                                }
                            ?>"

                            <?php

                                $moduleOptions = \Workspace\Module::getModuleOptions();
                                $joinClasses = $moduleOptions->getJoinClasses();
                                foreach ($joinClasses as $join) {
                                    if ($join['sourceEntity'] == $value['targetEntity'])
                                        continue;
                                }

                            ?>
                                href="<?=
                                    $this->url(
                                        'workspace/one-to-many',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $value['targetEntity'],
                                            'mappedBy' => $value['mappedBy'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($value['targetEntity']); ?>
                            </a>
                        </td>
                    </tr>

                            <?php

                            break;

                        case ClassMetadataInfo::MANY_TO_MANY: #8
                            ?>

                            <tr>
                                <td><?php  echo $this->escapeHtml($field); ?></td>
                                <td>

                            <a class="workspace btn btn-<?php
                                switch ($this->revisionEntity->getRevisionType()) {
                                    case 'INS':
                                        echo 'success';
                                        break;
                                    case 'UPD':
                                        echo 'warning';
                                        break;
                                    case 'DEL':
                                        echo 'danger';
                                        break;
                                    default:
                                        echo 'info';
                                }
                            ?>"

                            <?php
                            if (!isset($value['joinTable'])) {
                                // Handle inverse

                                // Find join table association where target and source are inverse of this association
                                // which will have the join table name
                                $moduleOptions = \Workspace\Module::getModuleOptions();
                                $joinClasses = $moduleOptions->getJoinClasses();
                                foreach ($joinClasses as $join) {
                                    if ($join['sourceEntity'] == $value['targetEntity'])
                                        continue;
                                }

                            ?>
                                href="<?=
                                    $this->url(
                                        'workspace/association-source',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $join['joinTable']['name'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($join['joinTable']['name']); ?>
                                <br>
                                (<?= $this->escapeHtml($join['sourceEntity']); ?>)
                            <?php
                            } else {
                                // Handle source
                                ?>
                                href="<?=
                                    $this->url(
                                        'workspace/association-target',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $value['joinTable']['name'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($value['joinTable']['name']); ?>
                                <br>
                                (<?= $this->escapeHtml($value['targetEntity']); ?>)
                            <?php
                            }
                            ?>
                            </a>
                        </td>
                    </tr>
                                <?php
                            break;

                        default:
                            break;
                    }

                ?>
            <?php
            }
        }
        ?>
    </tbody>
</table>


<form action="<?=
    $this->url('workspace/compare',
        array(
        )
    );
    ?>" method="post">

<?php
    $first = true;
    $oldSet = false;
    $paginator = $this->workspaceRevisionEntityPaginator($page, $this->revisionEntity->getWorkspaceEntity());
?>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Compare Revision Entities
    </caption>
    <thead>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'workspace/pagination/revision-entity',
                    array(
                        'route' => 'workspace/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Old</th>
            <th>New</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'workspace/pagination/revision-entity',
                    array(
                        'route' => 'workspace/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
    </tfoot>
    <tbody>
        <?php
        foreach ($paginator as $rev) {
        ?>
            <tr>
                <td>
                    <a href="<?=
                        $this->url('workspace/revision',
                            array(
                                'revisionId' => $rev->getRevision()->getId()
                            )
                        );
                    ?>">

                        <?= $rev->getRevision()->getId(); ?>
                        @ <?php echo $this->WorkspaceDateTimeFormatter($rev->getRevision()->getTimestamp()); ?>

                    </a>
                </td>

                <td>
                    <?= $this->workspaceRevisionEntityLink($rev); ?>
                </td>

                <td><?= $this->escapeHtml($rev->getRevision()->getComment()); ?></td>

                <td>
                <?= $this->partial(
                    'workspace/index/partial/user-button',
                    array('user' => $rev->getRevision()->getUser())
                );?>
                </td>

                <td>
                    <input type="radio" name="revisionEntityId_old" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if (sizeof($paginator) == 1 or ($rev == $this->revisionEntity and !$first) or (!$oldSet and !$first)) {
                            echo 'checked="checked"';
                            $oldSet = true;
                        }
                        ?> />
                </td>
                <td>
                    <input type="radio" name="revisionEntityId_new" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if ($first) {
                            echo 'checked="checked"';
                            $first = false;
                        }
                        ?> />
                </td>

            </tr>
            <?php
            }
            ?>
    </tbody>
</table>

    <input type="submit" class="workspace btn btn-primary" value="Compare revisions" />

</form>

    <a href="<?=
            $this->url(
                'workspace/entity',
                array(
                    'entityClass' => $this->revisionEntity->getWorkspaceEntity()->getWorkspaceEntityClass(),
                )
            );?>
    " class="workspace btn btn-primary">All Revisons for <?= $this->escapeHtml($this->revisionEntity->getWorkspaceEntity()->getWorkspaceEntityClass()); ?></a>
