<?= $this->partial('workspace/index/partial/navigation'); ?>

<?php
if ($user) {
    $userId = $user->getId();
?>
    <h1>Workspace for <?= $this->escapeHtml($user->getDisplayName()); ?></h1>
<?php
} else {
    $userId = null;
?>
<h1>Workspace Approved Revisions</h1>
Revisions which were automatically approved by Workspace
<?php
}
?>
<?php $paginator = $this->workspacePaginator($this->page, $this->userId); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
            </th>
        </tr>
        <?=
        $this->partial('workspace/index/partial/revision-table-header-row');
        ?>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
        <?php
        foreach ($paginator as $revision) {
            echo $this->partial('workspace/index/partial/revision-table-row', array(
                'revision' => $revision
            ));
        }
        ?>
    </tbody>
</table>
