<a class="btn btn-info pull-right" style="margin-left: 20px;" href="<?=
    $this->url('workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>

<a class="btn btn-info pull-right" href="<?=
    $this->url('workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>


<h1>Workspace for
<a " class="btn btn-default" href="<?php
    echo $this->url('workspace/user', array('userId' => $this->user->getId()));
    ?>">

    <h3>
        <?= $this->gravatar($this->user->getEmail(), array('img_size' => 36)); ?>
        <?= $this->user ?>
    </h3>
</a>
</h1>


</h1>

<?php $paginator = $this->workspacePaginator($this->page, $this->user->getId()); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Approval</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'workspace/pagination/revision', array('route' => 'workspace/page'));
            ?>
        </th>
    </tfoot>

    <tbody>
        <?=
        $this->partial('workspace/index/partial/revision-table-rows', array(
            'revisions' => $paginator,
        ));
        ?>
    </tbody>
</table>
