<span class="pull-right">

<a class="workspace btn btn-default" style="margin-left: 20px;" href="<?=
    $this->url('workspace/master');
?>"><i class="icon-code-fork"></i> Master</a>
&nbsp;

<a class="workspace btn btn-default" href="<?=
    $this->url('workspace/firehose');
?>"><i class="icon-bullseye"></i> Firehose</a>
&nbsp;

<?php
//if ($this->isAllowed('workspace/submitted')) {
?>
    <a class="workspace btn btn-default" href="<?=
        $this->url('workspace/submitted');
    ?>"><i class="icon-check-sign"></i> Submitted</a>
    &nbsp;
<?php
//}
?>

<?php
    if ($this->workspaceService()->getUser()) {
        echo $this->partial(
            'workspace/index/partial/user-button',
            array('user' => $this->workspaceService()->getUser()));
    }
?>
</span>
