<a href="<?=
    $this->url('workspace/revision',
        array('revisionId' => $this->revision->getId())
    );
?>" class="btn btn-approve-<?= $this->revision->getApprove(); ?>">
    <i class="icon-<?php
    switch ($this->revision->getApprove()) {
        case 'approved':
            echo 'check';
            break;
        case 'rejected':
            echo 'check-minus';
            break;
        case 'submitted':
            echo 'check-sign';
            break;
        case 'not submitted':
            echo 'check-empty workspace';
            break;
        default:
            echo '';
            break;
    }
    ?>"></i> <?= ucwords($this->revision->getApprove()); ?></a>


<?php
    if ($this->revision->getApprove() == 'approved') {
?>
        by
        <?= $this->partial(
            'workspace/index/partial/user-button',
            array('user' => $this->revision->getApproveUser())
        );?>

        <br><?= $this->WorkspaceDateTimeFormatter($this->revision->getApproveTimestamp()); ?>
<?php
    }
?>
