<?php
foreach ($revisions as $revision) {
?>
    <tr>
        <td>
            <a href="<?=
                $this->url('workspace/revision',
                    array(
                        'revisionId' => $revision->getId()
                    )
                );
            ?>">

                <?= $this->escapeHtml($revision->getId());?>
                @ <?php echo $this->WorkspaceDateTimeFormatter($revision->getTimestamp()); ?>

            </a>
        <br>

        <?php
        foreach ($revision->getRevisionEntities() as $revisionEntity) {
        ?>
            <div>
                <?= $this->workspaceRevisionEntityLink($revisionEntity); ?>
            </div>
        <?php
        }
        ?>
        </td>

        <td><?= nl2br($this->escapeHtml($revision->getComment())); ?></td>

        <td>
        <?= $this->partial(
            'workspace/index/partial/user-button',
            array('user' => $revision->getUser())
        );?>
        </td>

        <td>
                <i class="icon-<?php
                switch ($revision->getApprove()) {
                    case 'approved':
                        echo 'check';
                        break;
                    case 'rejected':
                        echo 'check-minus';
                        break;
                    case 'submitted':
                        echo 'check-sign';
                        break;
                    case 'not submitted':
                        echo 'check-empty workspace';
                        break;
                    default:
                        echo '';
                        break;
                }
                ?>"></i> <?= ucwords($revision->getApprove()); ?>


            <?php
                if ($revision->getApprove() == 'approved') {
            ?>
                    by
                    <?= $this->partial(
                        'workspace/index/partial/user-button',
                        array('user' => $revision->getApproveUser())
                    );?>

                    <br><?= $this->WorkspaceDateTimeFormatter($revision->getApproveTimestamp()); ?>
            <?php
                }
            ?>

            <?php
            if (in_array($revision->getApprove(), ['submitted']) and !$this->isAllowed('workspace/approve')) {
            ?>
                <br>
                <a href="<?= $this->url('workspace/approve', array('revisionId' => $revision->getId())); ?>" class="btn btn-inverse">
                    <i class="icon-check"></i>
                    Review Workspace
                </a>
            <?php
            }
            ?>

            <?php
            if ($this->zfcUserIdentity() == $revision->getUser()
                and in_array($revision->getApprove(), ['rejected', 'not submitted']
            )) {
            ?>
                <br>

                <a href="#" data-id="<?= $revision->getId(); ?>" class="btn btn-default workspace-revision-edit-comment">
                    <i class="icon-comment-alt"></i>
                    Edit Comment
                </a>

                <a href="<?=
                    $this->url('workspace/revision',
                        array('revisionId' => $revision->getId())
                    );
                ?>" class="btn btn-approve-<?= $revision->getApprove(); ?> workspace-revision-submit-for-approval"
                    data-id="<?= $revision->getId(); ?>"
                >
                    <i class="icon-check"></i>
                    Submit For Approval
                </a>
            <?php
            }
            ?>

            <?php
            if ($revision->getApproveMessage()) {
            ?>
            <div style="border: solid;border-color: #aaaaaa; border-width: 1px; border-radius:4px; padding: 4px;">
                <?= nl2br($this->escapeHtml($revision->getApproveMessage())); ?></div>
            <?php
            }
            ?>
        </td>
    </tr>
<?php
}

