<a href="<?=
    $this->url('stuki-workspace/revision',
        array('revisionId' => $this->revision->getId())
    );
?>" class="btn btn-approve-<?= $this->revision->getApprove(); ?>">
    <i class="icon-<?php
    switch ($this->revision->getApprove()) {
        case 'approved':
            echo 'check';
            break;
        case 'rejected':
            echo 'check-minus';
            break;
        case 'submitted':
            echo 'check-sign';
            break;
        case 'not submitted':
            echo 'check-empty';
            break;
        default:
            echo '';
            break;
    }
    ?>"></i> <?= ucwords($this->revision->getApprove()); ?></a>

<?php
    if ($this->revision->getApprove() == 'approved') {
?>
        by
        <a href="<?php
            if ($this->revision->getApproveUser()) {
                echo $this->url('stuki-workspace/user', array('userId' => $revision->getApproveUser()->getId()));
            } else {
                echo $this->url('stuki-workspace/user', array('userId' => '0'));
            }
        ?>" class="btn btn-default">
            <?php
                if ($revision->getApproveUser()) {
                    echo $this->gravatar($revision->getApproveUser()->getEmail(), array('img_size' => 24));
                    echo ' ';
                    echo $this->escapeHtml($revision->getApproveUser()->getDisplayName());
                } else {
                    echo $this->gravatar('stuki.org@gmail.com', array('img_size' => 24));
                    echo ' Stuki Workspace';
                }
            ?>
        </a>

        <br><?= $this->StukiDateTimeFormatter($this->revision->getApproveTimestamp()); ?>
<?php
    }
?>
